CREATE TABLE IF NOT EXISTS employees (
    emp_id INT(10) NOT NULL AUTO_INCREMENT,
    fname VARCHAR(45) DEFAULT NULL,
    lname VARCHAR(45) DEFAULT NULL,
    dob DATE DEFAULT NULL,
    doj DATE DEFAULT NULL
	    PRIMARY KEY (emp_id)
	    ) ENGINE=InnoDB
